// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Project: quikgroceries
/// Android app "customer new": com.quickgrocery.io
/// App ID: 1:970937777233:android:db7a0d4e8b73454f6e0c70
///
/// Regenerate: `flutterfire configure` from quickgrocery_user/
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd3A_4BYlsczbs76kU30p11o4-cwkFDK8',
    appId: '1:970937777233:android:db7a0d4e8b73454f6e0c70',
    messagingSenderId: '970937777233',
    projectId: 'quikgroceries',
    storageBucket: 'quikgroceries.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJT6hRIgonqKbbmAROsN7agaRtqGwe1TY',
    appId: '1:970937777233:ios:10b9106006f6e0c66e0c70',
    messagingSenderId: '970937777233',
    projectId: 'quikgroceries',
    storageBucket: 'quikgroceries.firebasestorage.app',
    iosBundleId: 'com.ahmed.quickgrocery',
  );
}
